# Example Wikibase docker-compose setup
version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: ${MW_ADMIN_NAME}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY}
  # Disable jobs running after requests when wikibase_jobrunner is defined
  MW_WG_JOB_RUN_RATE: 0
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}
  WIKIBASE_HOST: ${WIKIBASE_HOST}

services:
  pilote-fne-wikibase:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    container_name: pilote-fne-wikibase
    links:
      - pilote-fne-mysql
    depends_on:
      - pilote-fne-mysql
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    ports:
      - "${WIKIBASE_PORT}:80"
    volumes:
      ## This shares the configuration with jobrunner
      - shared:/var/www/html/:rw

      ## Uncomment this next line to mount your own LocalSettings.php file
      - ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php

    networks:
      default:
        aliases:
         - ${WIKIBASE_HOST}
         - wikibase-docker.svc
    environment:
      <<: *wikibase_variables
      WIKIBASE_PINGBACK:
      MW_WG_ENABLE_UPLOADS:

  pilote-fne-wikibase_jobrunner:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    container_name: pilote-fne-wikibase_jobrunner
    entrypoint: /bin/bash
    command:  /jobrunner-entrypoint.sh
    links:
      - pilote-fne-mysql
    depends_on:
      - pilote-fne-mysql
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    volumes:
      - shared:/shared/:ro
      - ./jobrunner-entrypoint.sh:/jobrunner-entrypoint.sh
    networks:
      default:
        aliases:
          - wikibase-jobrunner.svc
    environment:
      <<: *wikibase_variables
      MAX_JOBS: ${MAX_JOBS}

  pilote-fne-mysql:
#    image: "${MYSQL_IMAGE_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pilote-fne-mysql
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    ports:
      - 23306:3306  
    volumes:
      - ./volume_mysql:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    environment:
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
#      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_ROOT_PASSWORD_HASH_FILE: /run/secrets/mysql_root_password_hash
    secrets:
      - mysql_root_password_hash   
    networks:
      default:
        aliases:
         - mysql.svc
    sysctls:
      kernel.shmmax: 3758096384 
      kernel.shmall: 917504      
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  shared:
#  mediawiki-mysql-data:

secrets:
  mysql_root_password_hash:
    file: ./mysql_root_password_hash.txt # put root password hash to this file value calculated with SELECT PASSWORD('my-secret-pw')
